version: "3.8"

services:
  server:
    build: ./server
    ports:
      - "3000:3000"
    volumes:
      - ./server:/app
    restart: always

  client:
    build: ./client
    ports:
      - "8080:80"
    volumes:
      - ./client:/usr/share/nginx/html
    restart: always
