services:
  backend:
    build:
      context: ./server
    container_name: voicechat-server
    restart: always
    ports:
      - "10000:10000"
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://mongodb:27017/voicechat
      CLIENT_URL: "*"
      FORCE_HTTPS: "false"
      PORT: 10000

  mongodb:
    image: mongo:6
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: voicechat
    volumes:
      - mongo_data:/data/db
  
  frontend:
    build:
      context: ./client
    container_name: voicechat-frontend
    restart: always
    ports:
      - "8080:80"


volumes:
  mongo_data:
